baseURL: https://peng-chen-website.netlify.app/
languageCode: en-us
title: Portfolio website for Peng Chen
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    title: Hi, my name is Peng Chen, 陈鹏 in Chinese! Welcome :) !
  blog: {}
  contact:
    address:
      - city: London, NW8 7JN
        country: United Kingdom
        street: Morone House
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: pchen.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 07536943274
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/londonbschool/?hl=en
      - icon: fa-github
        label: GitHub
        url: https://github.com/Peng9899
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/peng-chen-b83187162/
  image: ''
  name: Your name
  navigation:
    links:
      - name: Home
        url: 'https://peng-chen-website.netlify.app/'
      - name: GITHUB
        url: https://github.com/Peng9899

    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: SOMETHING ABOUT ME
        title: My Story
        url: blogs/blog5
      - image: pic02.JPG
        subtitle: My Resume
        title: Academic and Professional
        url: blogs/Peng_Chen_CV.pdf
      - image: pic03.JPG
        subtitle: INSIGHT FROM GROUP ASSIGNMENT
        title: Data Analytics in Finance Experience
        url: blogs/magna
      - image: pic04.JPG
        subtitle: INSIGHT FROM MY WORK
        title: First meet with Data
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Happy to share with you
        title: Our Campus
        url: blogs/ipsum
      - image: pic06.JPG
        subtitle: FEEL FREE TO CONTACT ME
        title: My Linkedin
        url: https://www.linkedin.com/in/peng-chen-b83187162/

